### ISSUE TITLE
Support registering publishers using attributes

### ISSUE THREAD

**Issue by mauroservienti** [mauroservienti/NServiceBus.AttributeRouting#15]
Could be done using something like `[PublishedBy( "endpoint-name" )]`.

Need to understand how to detect if the transport need it or it can be simply skipped.

**Comment by SeanFeldman** [comment]
Broker based transports generally, with a few exceptions that are probably going to be addressed, do not require publisher information on the subscriber side.

**Comment by mauroservienti** [comment]
Agreed, this is the main reason is not available as a feature. I guess that in the long term on MSMQ might require this.

**Comment by SeanFeldman** [comment]
Long term and MSMQ sounds like an oxymoron 😃

**Comment by mauroservienti** [comment]
withdrawn.
